version: '3.4'

services:
    nginx:
        build:
            context: docker
            dockerfile: NginxDockerfile
        depends_on:
            - app
        networks:
            - frontend
        volumes:
            - .:/app

    app:
        build:
            context: .
            target: app-dev
        depends_on:
            - db
        networks:
            - frontend
            - backend
        volumes:
            - .:/app

    db:
        build:
            context: docker
            dockerfile: MysqlDockerfile
        environment:
          - MYSQL_ROOT_PASSWORD=forum
          - MYSQL_USER=forum
          - MYSQL_PASSWORD=forum
          - MYSQL_DATABASE=forum
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - backend

volumes:
    db_data:
        driver: local

networks:
    frontend:
    backend:
